language: node_js

node_js:
  - 'stable'

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

stages:
  - before test
  - test

jobs:
  include:
    - stage: before test
      script: npm migrate:up
    - stage: test
      script: npm test