language: node_js

node_js:
  - 'stable'

services:
  - postgresql

stages:
  - test

jobs:
  include:
    - stage: test
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
      script: npm run migrate:up
      script: npm run test
